### ISSUE TITLE
Cloned repo, but can't run pipenv

### ISSUE THREAD

**Issue by workingwriter** [Nycticorax/openSUSE-docs-revamped#2]
I'm following the instructions in the README, but have hit a dead-end. Probably my fault, but here's what I did.

1. Installed the Python3 Development pattern in YaST. 
2. Installed mkdocs with pip without creating the virtual environment first.
3. Installed pipenv with `pip3 install --user pipenv` the command provided by the README.
4. Added ~/.local.bin to PATH
5. Went away for awhile, which shouldn't matter, but for transparency...
6. Installed the GitHub command line tool from their zypper repo.
7. Successfully cloned this repo to a newly created 'DocRepo' dir in /home.
8. Ran 'pipenv install' from that dir. Shell told me to use cnf to find package.
9. Ran 'pip pipenv install' Pip thought long and hard and then gave me ERROR: unknown command "pipenv". Choosing 'pip3' didn't help.

Did you miss something? Should I start over?

**Comment by Nycticorax** [comment]
Hey Mike, thanks for letting me know.
To adress your points:
1. You don't need python3 development pattern. You can safely remove it, unless you need it for something else than this project. What you need is python3 (simpliciter). You can check you have it by running `python -V`. 
2. Doing that means that you get no value from pipenv. The point of pipenv is to let you instal almost every Python module from pipenv, and not from pip. The idea is to create separate little contexts that don't mess up with the global context of you system-wide Python installation. I would recommend that either you go for the pipenv approach (following this guide) or stick to the pip approach (in which case you're done after installing mkdocs from pip3 install etc: then you run your mkdocs commands from the `project` directory.
3. OK
4. OK
5. Where did you go? For how long? With WHOM?
6. OK!? (I thought openSUSE distro shipped with git out of the box)
7. OK
8. What is `cnf`? Make sure the directory from which you issue `pipenv install` contains (directly, not as part of a subdirectory) `Pipfile`.
9. NO-GO. Should have done instead `pipenv shell` from the Pipfile directory, and then, cd'ed into the `project` directory, from where you can finally run your mkdocs commands.

**Comment by badarotti** [comment]
If you're not a heavy user of pip, try skipping installing in a pipenv and see if that works. Just follow the simpler installation instructions on the mkdocs website and see if that solves your problems.

**Comment by badarotti** [comment]
>     4. Added ~/.local.bin to PATH

Also, this should be `~/.local/bin`

**Comment by Nycticorax** [comment]
@workingwriter Could you fix the issue? :)

**Comment by workingwriter** [comment]
Not getting anywhere. Reinstalled pipenv in the cloned repo directory (home/mikemc/Documentation/openSUSE-docs-revamped), where the pipfile is located. Confirmed that /home/mikemc/.local/bin/pipenv exists, and that /.local/bin is in the PATH.  And yes, Pipfile is in directory.

I run 'pipenv shell' and get ERROR: unknown command "pipenv".

**Comment by workingwriter** [comment]
Follow up: Leap runs Python 3.6.10. Reading the Pipfile, I need 3.8. True?

**Comment by Nycticorax** [comment]
"reinstalled pipenv in the cloned repo directory" sounds a little bit weird to me. Does it simply mean that you've run:
`pip3 install --user pipenv`
?
Once this is done, you simply `cd` into the directory containing the `Pipfile`, and run `pipenv install`. Then you `cd` into `project`, and can test out mkdocs commands such as `mkdocs build` and `mkdocs serve`.

**Comment by Nycticorax** [comment]
Mike told me privately he'd fixed it
