### ISSUE TITLE
Problems pushing using git

### ISSUE THREAD

**Issue by badarotti** [Nycticorax/openSUSE-docs-revamped#3]
Hi, I'm trying to push using git from my terminal and I'm getting the following error:
````
ERROR: Permission to Nycticorax/openSUSE-docs-revamped.git denied to badarotti.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
````
I'm not having problems pushing to my own repos? any idea on what is wrong or what I can check?
Thanks

**Comment by surprized** [comment]
It seems like you are writing directly to dev, did you try forking it first and then doing a pull request?
Unless you have write access, in that case then I don't know what went wrong.

**Comment by badarotti** [comment]
@surprized you are correct, I was writing directly to dev :sweat_smile:. Silly mistake, I usually have write access to the repos I work with. Thanks for the help.
